version: "3.8"
services:
  java-maven-app:
    image: vladibo/java-maven-app:1.2
    ports:
      - 8080:8080
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=lol
